export default {
  NAME: {
    JSON_BANK_ACCOUNT: 'JSON_BANK_ACCOUNT',
    DEPOSIT_HELP: 'TRANSLATABLE_HTML_HELP_DEPOSIT',
    WITHDRAW_HELP: 'TRANSLATABLE_HTML_HELP_WITHDRAW',
    EXCHANGE_HELP: 'TRANSLATABLE_HTML_HELP_EXCHANGE',
    TRANSFER_HELP: 'TRANSLATABLE_HTML_HELP_TRANSFER',
    PURCHASE_HELP: 'TRANSLATABLE_HTML_HELP_PURCHASE',
    BANNER_IMAGE_URL: 'URL_BANNER_IMAGE',
    BANNER_TITLE: 'TEXT_BANNER_TITLE',
    BANNER_SLOGAN: 'TEXT_BANNER_SLOGAN',
    ABOUT_US_URL: 'URL_ABOUT_US',
    HELP_HTML: 'TRANSLATABLE_HTML_HELP_APP',
    TAC_HTML: 'TRANSLATABLE_HTML_TERMS_APP',
    ASSET_CARD_IMAGE_URL: 'URL_ACCOUNT_IMAGE',
    DEPOSIT_AMOUNT_OPTIONS: 'DEPOSIT_AMOUNT_OPTIONS',
    URL_CUSTOMER_SERVICE: 'URL_CUSTOMER_SERVICE',
  },
};
